### ISSUE TITLE
Console Log in CompactShowLayout.js

### ISSUE THREAD

**Issue by shessafridi** [vdimitroff/ra-compact-ui#5]
![clg](https://user-images.githubusercontent.com/59542111/103101994-dd046680-463b-11eb-87fd-13cca6087882.PNG)

Getting a log in the console from CompactShowLayout.js line number 62

Code causing console log
`
 console.log('recursion', {
    index: index,
    props: props,
    child: child
  });
`

**Comment by vdimitroff** [comment]
Yes man, thanks - I am working on it - the issue with keys disappeared locally and shows up after the module is publish so had to put a console log to understand what's going on - will fix it as soon as I resolve the issue with the keys.

**Comment by vdimitroff** [comment]
Ok, this shoud be fixed now in version 1.0.16 - as well as the previous error in the console. Will wait for confirmation before closing the issue.

**Comment by shessafridi** [comment]
@vdimitroff Really sorry for the late reply, yeah the issue is no more thanks for this amazing library 😄.
