### ISSUE TITLE
maximum update depth exceeded when pressing enter on a multiline TextInput

### ISSUE THREAD

**Issue by shessafridi** [vdimitroff/ra-compact-ui#6]
This issue not present in V1.0.14, I haven't checked V1.0.15 but it's present in the latest version
The expected behaviour is enter should add a line break but instead the component freezes.

**Comment by shessafridi** [comment]
Bro any plans to fix this issue ? I am using this library in production so a fix would be great 🙂

**Comment by vdimitroff** [comment]
Hey there, last weeks have been quite busy - sorry for respondin that late :( 

Yes, I'll have a look and try to fix it asap!

**Comment by vdimitroff** [comment]
Well, maybe you have missed out a subtle detail - the ShowLayout components are ment to work together with Field-type components, not Input-type components. So all kind of issues could be expected when you mix these two.

Though I got your pain and why you tried to use it inside a form. I am working on a FormLayout wrapper similiar to the ShowLayout component which will allow you to do just what you wanted to. So stay tuned for this one to appear soon.

Cheers
